spring.application.name=gateway-service
server.port=8.8.

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Route to employee-service
spring.cloud.gateway.routes[0].id=employee-service
spring.cloud.gateway.routes[0].uri=lb://employee-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/employees/**, /auth/**
spring.cloud.gateway.routes[0].filters[0]=JwtAuthenticationFilter

# Route to leave-service
spring.cloud.gateway.routes[1].id=leave-service
spring.cloud.gateway.routes[1].uri=lb://leave-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/leaves/**
spring.cloud.gateway.routes[1].filters[0]=JwtAuthenticationFilter
